name: deploy_cloud

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: simple echo
        run: echo hello_world
      -
        name: run python 
        run: python ./main.py --token ${{ secrets.TOKEN }} --date 2023-01-05 --ville Rennes
