name: deploy
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
    name : simple echo
    run: echo hello
      -
    name : run script
    run : python main.py
    
