name: deploy_cloud

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: simple echo
        run: echo hello_world
      -
        name: install requirements
        run: pip install -r requirements.txt
      -
        name: docker build image
        run: docker build . --file Dockerfile --tag sncf-on-time:$GITHUB_SHA
      -     
        name: 'Authenticate to Google Cloud'
        uses: 'docker/login-action@v2'
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{secrets.GOOGLE_CREDENTIALS }}
      - 
        name: Tag the Docker image
        run: docker tag sncf-on-time:$GITHUB_SHA europe-west1-docker.pkg.dev/ensai-2023-373710/ja-depot/sncf-on-time:$GITHUB_SHA
      -
        name: docker push image
        run: docker push europe-west1-docker.pkg.dev/ensai-2023-373710/ja-depot/sncf-on-time:$GITHUB_SHA
      
